### ISSUE TITLE
[Feature Request]: Add/delete field or tags in multiple files

### ISSUE THREAD

**Issue by Yaozhuwa** [mdelobelle/obsidian_supercharged_links#17]
This plugin is very helpful to visualize my note. However, there is no way to add/delete tags or field value to multiple files at once.
For I don't use field value before, I have to add tags or field value to each file manually, which is a disaster for me.

Feature request:
- Select multiple files in file Explorer within Obsidian
- Right click to add field or tags for the files selected.

**Comment by mdelobelle** [comment]
Hello, thank you for your idea. 
This could be quite difficult to achieve because you can't be sure that all the selected files have the same structure (there is no dedicated section for inline fields for example) and therefore, bulk modifying files to add or delete elements may cause damages to one of the file.
A solution so avoid those issues could be to have a file-by-file validation of where in the file the plugin should add/delete the field.... but then it wouldn't improve so much the user experience from the current situation

**Comment by javiavid** [comment]
That's one of the things I miss about Notion.

Has anything changed in obsidian since june to improve this?
Could this be done using the multiple cursor?
